name: macOS

on:
  push:
    paths:
      - 'macOS/**'

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install package
      run: |
        brew install shellcheck

    - name: Lint macOS/install.sh
      working-directory: ./macOS
      run: shellcheck --exclude SC2016,SC1004 install.sh

    - name: Run macOS/install.sh
      working-directory: ./macOS
      run: SH_ENV=CI ./install.sh

    - name: Upload result for macOS/install.sh
      uses: actions/upload-artifact@v1
      with:
        name: Script Result
        path: c000000i.log
