name: macOS

on:
  push:
    paths:
      - 'macOS/**'

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install package
      run: |
        brew install shellcheck

    - name: Lint macOS/install.sh
      working-directory: ./macOS
      run: shellcheck install.sh
