name: macOS

on:
  push:
    paths:
      - 'macOS/**'
      - 'github/workflows/ci-mac-os.ym'

jobs:
  macos-test:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./macOS

    steps:
    - uses: actions/checkout@v2

    - name: Install package
      run: |
        brew install shellcheck

    - name: Lint macOS/install.sh
      run: shellcheck --exclude SC2016,SC1004 install.sh

    - name: Lint macOS/java.sh
      run: shellcheck java.sh

    - name: Run macOS/install.sh
      run: ./install.sh
      env:
        ENV: CI

    - name: Run macOS/java.sh
      run: ./java.sh

    - name: Upload result for macOS/install.sh
      uses: actions/upload-artifact@v1
      with:
        name: Script Result
        path: macOS/macOS-ci.log
