name: windows

on:
  push:
    paths:
      - 'windows/**'

jobs:
  windows-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        working-directory: ./windows

    steps:
    - uses: actions/checkout@v2

    - name: Install package
      run: |
        Install-Module -Name PSScriptAnalyzer

    - name: Lint windows/install.ps1
      run: Invoke-ScriptAnalyzer install.ps1

    - name: Run windows/install.ps1
      run: ./install.ps1
      env:
        ENV: CI
